-- MySQL Script generated by MySQL Workbench
-- Sat May 20 18:07:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydbpokemon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydbpokemon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydbpokemon` DEFAULT CHARACTER SET utf8 ;
USE `mydbpokemon` ;

-- -----------------------------------------------------
-- Table `mydbpokemon`.`tipo_pokemon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbpokemon`.`tipo_pokemon` (
  `cod_tipo_pokemon` INT NOT NULL AUTO_INCREMENT,
  `des_tipo_pokemon` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`cod_tipo_pokemon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbpokemon`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbpokemon`.`region` (
  `cod_region` INT NOT NULL AUTO_INCREMENT,
  `des_region` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`cod_region`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbpokemon`.`pokemon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbpokemon`.`pokemon` (
  `cod_pokemon` INT NOT NULL AUTO_INCREMENT,
  `nombre_pokemon` VARCHAR(25) NOT NULL,
  `punto_salud` INT NOT NULL,
  `punto_ataque` INT NOT NULL,
  `punto_defensa` INT NOT NULL,
  `punto_velocidad` INT NOT NULL,
  `habilidad_secreta` TINYINT NOT NULL,
  PRIMARY KEY (`cod_pokemon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbpokemon`.`pokemon_tipo_pokemon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbpokemon`.`pokemon_tipo_pokemon` (
  `cod_pokemon` INT NOT NULL,
  `cod_tipo_pokemon` INT NOT NULL,
  `doble_tipo` TINYINT NOT NULL,
  `legendario` TINYINT NOT NULL,
  PRIMARY KEY (`cod_pokemon`, `cod_tipo_pokemon`),
  INDEX `fk_pokemon_has_tipo_pokemon_tipo_pokemon1_idx` (`cod_tipo_pokemon` ASC),
  INDEX `fk_pokemon_has_tipo_pokemon_pokemon_idx` (`cod_pokemon` ASC),
  CONSTRAINT `fk_pokemon_has_tipo_pokemon_pokemon`
    FOREIGN KEY (`cod_pokemon`)
    REFERENCES `mydbpokemon`.`pokemon` (`cod_pokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pokemon_has_tipo_pokemon_tipo_pokemon1`
    FOREIGN KEY (`cod_tipo_pokemon`)
    REFERENCES `mydbpokemon`.`tipo_pokemon` (`cod_tipo_pokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbpokemon`.`region_pokemon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbpokemon`.`region_pokemon` (
  `cod_pokemon` INT NOT NULL,
  `cod_region` INT NOT NULL,
  `version_regional` TINYINT NOT NULL,
  PRIMARY KEY (`cod_pokemon`, `cod_region`),
  INDEX `fk_pokemon_has_region_region1_idx` (`cod_region` ASC),
  INDEX `fk_pokemon_has_region_pokemon1_idx` (`cod_pokemon` ASC),
  CONSTRAINT `fk_pokemon_has_region_pokemon1`
    FOREIGN KEY (`cod_pokemon`)
    REFERENCES `mydbpokemon`.`pokemon` (`cod_pokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pokemon_has_region_region1`
    FOREIGN KEY (`cod_region`)
    REFERENCES `mydbpokemon`.`region` (`cod_region`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbpokemon`.`condicion_evolucion_pokemon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbpokemon`.`condicion_evolucion_pokemon` (
  `cod_evolucion_pokemon` INT NOT NULL AUTO_INCREMENT,
  `evolucion_por_experiencia` TINYINT NOT NULL,
  `megaevolucion` TINYINT NOT NULL,
  `evolucion_por_objeto` TINYINT NOT NULL,
  PRIMARY KEY (`cod_evolucion_pokemon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbpokemon`.`pokemon_condicion_evolucion_pokemon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbpokemon`.`pokemon_condicion_evolucion_pokemon` (
  `cod_pokemon` INT NOT NULL,
  `cod_evolucion_pokemon` INT NOT NULL,
  PRIMARY KEY (`cod_pokemon`, `cod_evolucion_pokemon`),
  INDEX `fk_pokemon_has_evolucion_pokemon_evolucion_pokemon1_idx` (`cod_evolucion_pokemon` ASC),
  INDEX `fk_pokemon_has_evolucion_pokemon_pokemon1_idx` (`cod_pokemon` ASC),
  CONSTRAINT `fk_pokemon_has_evolucion_pokemon_pokemon1`
    FOREIGN KEY (`cod_pokemon`)
    REFERENCES `mydbpokemon`.`pokemon` (`cod_pokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pokemon_has_evolucion_pokemon_evolucion_pokemon1`
    FOREIGN KEY (`cod_evolucion_pokemon`)
    REFERENCES `mydbpokemon`.`condicion_evolucion_pokemon` (`cod_evolucion_pokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
